name: docs-preview

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
  push:

jobs:
  build-html:
    if: ${{ github.event.pull_request.action == 'opened' || github.event.pull_request.action == 'synchronize' || github.event_name == 'push' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9.7]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Sphinx==3.5.4
      - name: Make HTML
        run: |
          pushd docs
          make html
          popd
      - name: HTML directory for merge
        if: github.ref == 'refs/heads/main'
        run: echo "HTML_DIR=main" >> $GITHUB_ENV
      - name: HTML directory for review
        if: github.ref != 'refs/heads/main'
        run: echo "HTML_DIR=review/branch-${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs/build/html
          target-folder: ${{ env.HTML_DIR }}

  remove-html:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.head.ref != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: HTML directory for review
        run: echo "HTML_DIR=review/branch-${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
      - name: Delete preview HTML
        run: rm -rf ${{ env.HTML_DIR }}
