name: docs-preview-pr

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  build-html-pr:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - name: Information
        run: echo  'PR \#${{ github.event.pull_request.number }} from ${{ github.event.pull_request.head.label }}'

