name: docs-preview-pr

on:
  workflow_run:
    workflows: [build]
    types: [completed]

env:
  WF_ID: ${{ github.event.workflow_run.id }}

jobs:
  remove:
    uses: nvidia-merlin/.github/.github/workflows/docs-preview-pr.yaml@docs-chore
