name: docs-preview-pr

on:
  workflow_run:
    workflows: [build]
    types: [completed]

jobs:

  # Check that the target repository of the PR is configured for GitHub Pages.
  echo-job:
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Echo event
        env:
          WF_ID: ${{ github.event.workflow_run.id }}
        run: |
          gh run view "${WF_ID}"
          gh run download "${WF_ID}"
          cat ./pr/pr.txt
          ls -asl ./html-build-artifact/
